image:
  name: registry.gitlab.com/dreae/sourcemod-build:latest
  entrypoint: ["/bin/bash", "-c"]

build:
  script:
  - dnf -y install make
  - cp include/*.inc /sourcemod/scripting/include
  - make CC=/sourcemod/scripting/spcomp all
  - mkdir plugins
  - cp compiled/*.smx plugins/
  - mkdir scripting
  - cp *.sp scripting/
  - cp -r include/ scripting/
  artifacts:
    paths:
      - plugins/
      - translations/
      - sound/
      - scripting/