image:
  name: registry.gitlab.com/dreae/sourcemod-build:latest
  entrypoint: ["/bin/bash", "-c"]

build:
  script:
  - dnf -y install make
  - mkdir compiled
  - make CC=/sourcemod/scripting/spcomp INCLUDE="-i /sourcemod/scripting/include -i include" all
  - mkdir plugins
  - cp compiled/*.smx plugins/
  - mkdir scripting
  - mkdir -p addons/sourcemod
  - cp *.sp scripting/
  - cp -r include/ scripting/
  - cp -r configs/ addons/sourcemod
  - cp -r scripting/ addons/sourcemod
  - cp -r plugins/ addons/sourcemod
  - cp -r translations/ addons/sourcemod

  artifacts:
    paths:
      - addons/
      - sound/